### ISSUE TITLE
Trying to create a project with graphql and the solution is empty

### ISSUE THREAD

**Issue by ddieppa** [Dotnet-Boxed/Templates#1034]
### The Bug
Go to Visual studio, create a new solution, search for boxed, select in the results the graphql one, leave all the defaults and then nothing happens, when go to the folder, there is a solution and folder but empty, when opened the solution file is just an empty solution

### Expected behaviour

Should be a project with a graphql and hotchocolate server in place

### Project template

ASP.NET Core Graphql boxed

## Environment

Visual Studio 2019 preview latest with all the latest sdk

**Comment by ddieppa** [comment]
In Rider is working fine, the only thing is that does not allows me to select options, just create the project with the defaults?

**Comment by RehanSaeed** [comment]
You have to enable the preview option under the options.

Last I tested with 16.9 with the preview feature enabled, I could see the options but VS would create a new solution instead of using the one supplied in the template. The workaround was to close the solution created by VS and open the other one in the project.

The bug above occurs because VS 16.9 does not currently support full solution templates. This will come in VS 16.10 Preview 2. When 16.10 gets released I also need to merge https://github.com/Dotnet-Boxed/Templates/pull/1017 to enable the feature. There are links in the PR to issues with more info.

**Comment by RehanSaeed** [comment]
VS 16.10 has been released with full support for solution templates:

https://rehansaeed.com/dotnet-boxed-visual-studio-integration/
