### ISSUE TITLE
UseCors must be called before UseResponseCaching

### ISSUE THREAD

**Issue by lamLeX** [Dotnet-Boxed/Templates#1106]
### Describe the bug

According to https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-5.0
![image](https://user-images.githubusercontent.com/4281894/116504486-39d39000-a86d-11eb-87bf-d0d913f78e1e.png)

### Project template

Api 6.2.1

**Comment by lamLeX** [comment]
Also, in https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0#set-the-allowed-origins
![image](https://user-images.githubusercontent.com/4281894/116510705-2da1ff80-a87a-11eb-8f38-b056b746ca1c.png)

Is there any specific reason why this template relaxes all CORS security feature?

**Comment by RehanSaeed** [comment]
Thanks for the bug. Looks like this is a recent change in documentation https://github.com/dotnet/aspnetcore/issues/23218.

Fixed by https://github.com/Dotnet-Boxed/Templates/pull/1111.

**Comment by RehanSaeed** [comment]
Regarding `AllowAnyOrigin and AllowCredentials`, we don't specify both together in the template. We only enable `AllowAnyOrigin` because this is a common thing to do. Since this is a template, it's up to the developer to extend as they wish. With that said, we could introduce more secure defaults. What do you suggest?
