### ISSUE TITLE
status 406 when validation fails (should be status 400)

### ISSUE THREAD

**Issue by senneclaeskens** [Dotnet-Boxed/Templates#459]
### Describe the bug

The POST method of the Cars controller returns a 406 status if you remove the value of a property which is marked as [Required].

### To Reproduce
POST the following json in swagger:
`{
  "cylinders": 6,
  "make": "",
  "model": "Civic"
}`

`[Required]
 public string Make { get; set; }`

### Expected behaviour

This should return Status400BadRequest with ProblemDetails as a response.

### Project template

ApiTemplate

## Environment

VS2019, .NET Core 3.1, I'm using the template which is on the master branch but not released through nuget yet. But I don't think this changes anything regarding this error.

**Comment by RehanSaeed** [comment]
This is probably because of the `Accept` HTTP header you are passing. When there is a validation error the API returns `application/problem+json`. If your `Accept` header does not contain `application/problem+json` or `application/json` or `*` then you will get 406 as the API doesn't know how to return something you understand.

Please reopen if I'm wrong.

**Comment by senneclaeskens** [comment]
Correct! If I manually do this request with following accept header, it returns me the correct information;

application/problem+json

But, shouldn't this be added to the swagger functionality?

**Comment by RehanSaeed** [comment]
The swagger has the option to select `application/json`.
