### ISSUE TITLE
New templates: OData, Uno Platform, ReactiveUI

### ISSUE THREAD

**Issue by weitzhandler** [Dotnet-Boxed/Templates#488]
Hi,

I just learned about this repo and it looks interesting.

I'm wondering if you'd consider additional templates such as:

- OData/Restier
  - ASP.NET Core Restier/OData server side project
  - Console client side app demonstrating basic usage using Simple.OData.Client
- Uno Platform
- ReactiveUI (WPF/UWP/WinUI/Uno)

What would it take to create such templates? Can I contribute?

**Comment by RehanSaeed** [comment]
Thanks for the suggestions. I'm generally accepting of contributions but careful about adding new project templates because I've learned that it is a **lot** of work to maintain a template over time.

## OData/RESTier

I'm not familiar with this library and haven't used OData for some time. I looked to use OData in the earliet days of ASP.NET Core but it hadn't been implemented yet. I suppose this changes things.

Judging by the number of GitHub starts the project has, it's not very popular yet, although the NuGet packages are still release candidates, so I guess it's very new. I'm hesitant to add something that has not yet released a stable version but I can be persuaded. Would this be a new template or an option to add to the API template.

## Uno

This is a very interesting framework that I've read about but not yet tried. Do they have their own template already? What would you add to the template? I can't envisage adding much apart from NuGet packages and a new empty window.

I've been expecting Microsoft to port UWP to Android and perhaps other platforms for a few years and going on the announcements at Build, it may finally be coming. Uno supports a lot more platforms though I think. This space is open.

## ReactiveUI

Which platform would you use it with? WPF? UWP? Doing them all might be too much.

I looked into this library some years ago when it was fairly new and used with WPF. I wrote a series of blog posts on Rx at the time. I'm not a fan of using Rx everywhere as this framework did at the time. There is a lot of overlap of Rx with `async`/`await` and especially now with `IAsyncEnumerable`. I think both of these idioms are easier to reason about than Rx observables. Has much changed?

**Comment by weitzhandler** [comment]
### OData

> I'm not familiar with this library and haven't used OData for some time. I looked to use OData in the earliet days of ASP.NET Core but it hadn't been implemented yet. I suppose this changes things.

[OData](https://docs.microsoft.com/en-us/odata/overview) used to be a major thing back in the days, then it lost its shine. Recently MS is reviving this library, and especially so with [Restier](https://github.com/OData/RESTier) which IS new.

### Uno

> Do they have their own template already?

Yes, they do, they even offer a VS [templates-extension](https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin). The generated app includes an independent regular UWP that runs on Android, iOS, and WASM, and as a matter of fact, [they just announced](https://platform.uno/uno-platform-2-0-reloaded-general-availability-hot-reload-and-more/) version 2.0, which offers simultaneous hot-reload in all platforms and other improvements.

### RxUI

> I'm not a fan of using Rx everywhere

You should use it when you want to work with a push-based model, as opposed to pull-based (enumerables), and stick to enumerables when you want to pull. I also like the power of defining your app in a functional pipeline manner, so your VM is divided in problem-specific chunks rather than your code scattered around in the VMs.

> There is a lot of overlap of Rx with `async`/`await` and especially now with `IAsyncEnumerable`

Not sure about `IAsyncEnumerable`, but Rx definitely developed in the cooperation with `Task`s and offers easy creation of observables from tasks and vice versa.

### Bottom line

> Which platform would you use it with? WPF? UWP? Doing them all might be too much.

What I was aiming for, was a cross-platform LoB app template that consists of all the three. Built with Uno hence running on every platform, powered by RxUI as underlying MVVM framework, and consisting of a server and client interaction app, that uses OData to pass data along. Probably also [`Microsoft.Extensions.*`](https://github.com/aspnet/Extensions) (it's .NET Standard) that has official integration with RxUI, to deal with [app-hosting](https://www.nuget.org/packages/Microsoft.Extensions.Hosting/) and bootstrapping, [dependency-injection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/), [logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging/), and [HttpClient factory pattern](https://www.nuget.org/packages/Microsoft.Extensions.Http/)

**Comment by RehanSaeed** [comment]
I wouldn't want to do a project template with such a wide scope. OData does not necessarily need to be used with a desktop application but if you tie it to a desktop app in the template it limits the flexibility and the number of people who might find it useful. Separate templates would be more flexible and cater to more developers.

**Comment by weitzhandler** [comment]
> OData does not necessarily need to be used with a desktop application but if you tie it to a desktop app in the template it limits the flexibility

That's why I want to go with Uno, it's Desktop, mobile, and web, you pick.

**Comment by RehanSaeed** [comment]
Apologies for coming back to this so late. Things got on top of me.

Microsoft released [MAUI](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/) at Build 2020. Not looked in detail yet but looks like it competes directly with Uno.

I think I'll avoid doing a desktop template for now. Web templates need a lot of boilerplate to do things right but with a desktop template it's unclear what I can add while still be unopinionated. Also, there are already templates out there for them.

Right now, I'd like to add a template for https://github.com/microsoft/reverse-proxy which I think would get quite a lot of use.

**Comment by VictorioBerra** [comment]
@RehanSaeed Why would people want to build their own Reverse Proxy instead of using:

- IIS
- Apache
- AWS ALB
- AWS ELB
- Caddy
- HAProxy
- lighttpd
- nginx
- Oracle HTTP
- Tomcat
- Traefik

It sounds like YARP is for people internal to Microsoft who need to do crazy things at scales most people do not need to worry about.

**Comment by RehanSaeed** [comment]
Apparently it will faster than NGINX which is faster than Traefik (I've used both). Also, instead of weird custom configuration you have to do for each product, this one will just be C# code and very easy to configure. Adding a LetsEncrypt option will be very simple too with a few lines of code. You also get the simple configuration methods that come with ASP.NET Core.

I'm guessing it's more geared towards Kubernetes which makes sense. I assume there will be some middleware to extend Kubernetes and be a proper reverse proxy in that space.

**Comment by VictorioBerra** [comment]
You're selling it a bit now ;)

Will it use this for LetsEncrypt? https://github.com/natemcmaster/LettuceEncrypt

**Comment by RehanSaeed** [comment]
Yes. It doesn't support wildcard certificates or DNS renewal yet though.
