### ISSUE TITLE
Project structure more streamlined with other dotnet core projects

### ISSUE THREAD

**Issue by kirkone** [Dotnet-Boxed/Templates#750]
Hi,

I want to ask if it is a good idea to have the outcome of this templates more like it is discussed here:
https://gist.github.com/davidfowl/ed7564297c61fe9ab814

The biggest change would be to have the `src` and `tests` folders and sort the projects in there.

I see some benefits in doing so, what do you think?

**Comment by RehanSaeed** [comment]
What benefits do you see to changing `Source` to `src` and `Tests` to `tests`?

**Comment by kirkone** [comment]
I think the main benefit will be, that more projects use this kind of conventions. So, it would be easier to switch between projects for example.
The complete "project structure in the dotnet core" world needs some kind of standard, so I thought it would be a good idea to start with a template than.

The discussion started by @davidfowl showed up some good results that should be used in more projects.

I know this will be a change with many consequences but discussing these can be helpful in learning something new for me.

**Comment by RehanSaeed** [comment]
I don't think there will ever be a standard directory structure. The directory structure we use is very similar to David's. The only real difference is that he's using shortened abbreviations. 

One reason to go with abbreviations is that Windows used to have a 256 character file path limit but I believe that problem is solved. Using full names is not more unclear than using abbreviations but it may be clearer for new developers.

**Comment by kirkone** [comment]
good point.
So I will close this.

**Comment by RehanSaeed** [comment]
Thank you for the suggestion!
