### ISSUE TITLE
Can not access Orleans Dashboard in Microsoft Orleans Boxed template

### ISSUE THREAD

**Issue by cuno92** [Dotnet-Boxed/Templates#751]
### To Reproduce

A link to some code to reproduce the bug can speed up a fix. Alternatively, show steps to reproduce the behaviour:

1. Start Server project
2. Go to Orleans  admin dashboard via localhost:8080 but can't reach

### Expected behaviour

Access to admin dashboard for Microsoft Orleans via localhost:8080

### Project template

Microsoft Orleans Boxed latest

## Environment

Which version of Visual Studio and the dotnet SDK were you using?
dotnet-sdk-3.1.401-win-x64

**Comment by RehanSaeed** [comment]
You need to start the Azure Storage Emulator. The Orleans template uses Azure Storage for storage because it's cheap and fast. I could have used in-memory storage but you can't use that in production which makes it useless. This template is intended to be used in production.

![image](https://user-images.githubusercontent.com/2270364/90486380-c0f23500-e130-11ea-995f-c96f1ff00958.png)

![image](https://user-images.githubusercontent.com/2270364/90486280-a1f3a300-e130-11ea-946d-d8712228678f.png)
